version: "3.9"
services:
  zookeeper:
    image: zookeeper

  kafka0:
    depends_on:
      - zookeeper
    image: thebinary/kafka:2.13-2.7.0
    build:
      context: ../../
      args:
        KAFKA_VER: 2.7.0
        SCALA_VER: 2.13
    volumes:
      - type: bind
        source: ./broker0
        target: /etc/kafka

  kafka1:
    depends_on:
      - zookeeper
    image: thebinary/kafka:2.13-2.7.0
    build:
      context: ../../
      args:
        KAFKA_VER: 2.7.0
        SCALA_VER: 2.13
    volumes:
      - type: bind
        source: ./broker1
        target: /etc/kafka

  kafka2:
    depends_on:
      - zookeeper
    image: thebinary/kafka:2.13-2.7.0
    build:
      context: ../../
      args:
        KAFKA_VER: 2.7.0
        SCALA_VER: 2.13
    volumes:
      - type: bind
        source: ./broker2
        target: /etc/kafka